name: Test Component
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Testing Component
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --ci

      - name: Run tests
        run: bun run test
